### ISSUE TITLE
wtf

### ISSUE THREAD

**Issue by Teicu** [suuhm/smtp_smuggling_checker.py#1]
so the script is **smtp_smuggler_poc.py** 

then you call it **smtp_smuggling_checker.py** 

in the screenshot is **smtp_poc-new.py**  

How to use:

usage: **smtp_smuggle.py** 

why do you use 4 different names for one script? who the hell understands anything anymore? lmao

**Comment by suuhm** [comment]
Hey sorry for confusion here :\
I've updated it in the readme so you can simply download the python file in frepo and run like:

````bash
# Example : You have to setup the Parameters with the right values!
#
.\smtp_smuggler_poc.py --server mail.server.com --port 587 --user user@server.com --rcpt vic@server.com --mode def
````
